name: Continuous integration
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn vscode:prepublish
      - uses: actions/upload-artifact@v2
        with:
          name: extension-artifact
          path: ./*.vsix
